### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeahwu**
理论上mac也是可以用的。让大家试试

### CODE REVIEW

**Comment by xyuanmu** [comment]
我看了XX-Net的库文件，darwin和linux是分开的，估计不通用，所以还是等有mac os的用户测试后再加上吧。

**Comment by yeahwu** [comment]
好吧，其实俺也是简单看鸟下goagent的py文件。嗯，俺也没有那高贵的系统。

**Comment by ahjsrhj** [comment]
...
mac 用户运行报错
$ python proxy.py
Traceback (most recent call last):
  File "proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
ImportError: No module named OpenSSL

用python2.6重试依然报错
$ python2.6 proxy.py
--------------------------------------------------------------------------------
XX-Mini Version     : 1.2.3 (python/2.6.9 pyopenssl/0.13.1)
Listen Address      : 127.0.0.1:8087
Setting File        : proxy.ini
GAE APPID           : xxxxxxxxxxxxxxxxxxxxxxxx
Pac Server          : http://127.0.0.1:8086/proxy.pac
CA File             : http://127.0.0.1:8086/CA.crt
Pac File            : file:///Users/xxx/Desktop/XX-Mini_linux_darwin_v1.2.3/data/proxy.pac
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "proxy.py", line 104, in <module>
    import proxy_handler
  File "/Users/xxx/Desktop/XX-Mini_linux_darwin_v1.2.3/lib.egg/lib/proxy_handler.py", line 21, in <module>
  File "/Users/xxx/Desktop/XX-Mini_linux_darwin_v1.2.3/lib.egg/lib/gae_handler.py", line 23, in <module>
  File "/Users/xxx/Desktop/XX-Mini_linux_darwin_v1.2.3/lib.egg/lib/connect_manager.py", line 15, in <module>
  File "/Users/xxx/Desktop/XX-Mini_linux_darwin_v1.2.3/lib.egg/lib/socks.py", line 207
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

**Comment by xyuanmu** [comment]
安装pyOpenSSL

**Comment by jzp820927** [comment]
brew install pyopenssl

**Comment by ahjsrhj** [comment]
使用`$ brew install pyopenssl`报错如下：
```
Error: No available formula with the name "pyopenssl"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```
Google之后使用如下方式解决
```sh
$ brew install libffi
$ easy_install PyOpenSSL
$ easy_install PyCrypto
```

**Comment by jzp820927** [comment]
还是 Linux 方便，一个 pyopenssl 就搞定了/

**Pull request closed without merging**
